#!/usr/bin/env node
// Generate audio/tts/<hash>.mp3 for every entry in texts.json (run collect.mjs first).
// Pipeline per text: VOICEVOX audio_query -> synthesis (wav) -> ffmpeg pipe -> mp3.
// Skips entries whose mp3 already exists unless --force.
// Writes audio/tts/manifest.js for the frontend.
//
// Optional filter: --only <comma list of source prefixes>
//   e.g. --only grammar-n5,grammar-n4   (great for phased rollout / testing)

import fs from 'node:fs';
import path from 'node:path';
import {
  ROOT, OUT_DIR, MANIFEST_JS, TEXTS_JSON,
  loadOverrides, applyOverrides,
  audioQuery, synthesis, checkEngine, wavToMp3,
} from './_lib.mjs';

const args = process.argv.slice(2);
const force = args.includes('--force');
const onlyIdx = args.indexOf('--only');
const onlyFilter = onlyIdx >= 0 ? new Set(args[onlyIdx + 1].split(',')) : null;

fs.mkdirSync(OUT_DIR, { recursive: true });

const ver = await checkEngine();
console.log(`VOICEVOX ${ver} reachable, output=${path.relative(ROOT, OUT_DIR)}/`);

const texts = JSON.parse(fs.readFileSync(TEXTS_JSON, 'utf8'));
const overrides = loadOverrides();

// Filter texts to generate this run.
const work = onlyFilter
  ? texts.filter(t => t.sources.some(s => onlyFilter.has(s.split('#')[0])))
  : texts;
console.log(`Targets: ${work.length}/${texts.length}${onlyFilter ? ' (filtered: --only ' + [...onlyFilter].join(',') + ')' : ''}`);

function writeManifest() {
  const manifest = {};
  for (const t of texts) {
    const mp3 = path.join(OUT_DIR, `${t.hash}.mp3`);
    if (fs.existsSync(mp3)) manifest[t.text] = t.hash;
  }
  const js = `// Generated by scripts/tts/generate.mjs — do not edit by hand.\nwindow.__TTS = ${JSON.stringify(manifest)};\n`;
  fs.writeFileSync(MANIFEST_JS, js, 'utf8');
  return Object.keys(manifest).length;
}

// Flush manifest up-front so already-generated files are reachable from the page during this run.
writeManifest();

let made = 0, skipped = 0, failed = 0;
let consecutiveFailures = 0;
const startMs = Date.now();
for (let i = 0; i < work.length; i++) {
  const { text, hash } = work[i];
  const mp3 = path.join(OUT_DIR, `${hash}.mp3`);
  if (!force && fs.existsSync(mp3)) { skipped++; continue; }
  const fed = applyOverrides(text, overrides);
  try {
    const q = await audioQuery(fed);
    const wav = await synthesis(q);
    wavToMp3(wav, mp3);
    made++;
    consecutiveFailures = 0;
    if (made % 25 === 0) {
      const elapsed = (Date.now() - startMs) / 1000;
      const rate = made / elapsed;
      const remaining = (work.length - i - 1) / rate;
      const total = writeManifest();
      console.log(`  ${i + 1}/${work.length} (made=${made}, manifest=${total}, ${rate.toFixed(1)}/s, ETA ${(remaining / 60).toFixed(1)}m)`);
    }
  } catch (e) {
    failed++;
    consecutiveFailures++;
    console.error(`  FAIL "${text.slice(0, 30)}…": ${e.message}`);
    // If the engine is in a bad state, blindly retrying makes it worse. Bail out and tell
    // the user to restart VOICEVOX. They can re-run the script and we'll skip what's done.
    if (consecutiveFailures >= 5) {
      console.error(`\nABORT: ${consecutiveFailures} consecutive failures — VOICEVOX engine looks wedged.`);
      console.error(`Quit the VOICEVOX app (Cmd+Q), reopen it, then re-run this script. Already-made files will be skipped.`);
      break;
    }
  }
}

const finalCount = writeManifest();

console.log(`\nDone. made=${made} skipped=${skipped} failed=${failed}`);
console.log(`Manifest entries: ${finalCount} → ${path.relative(ROOT, MANIFEST_JS)}`);
